### PR TITLE
FAQ

### PR DESCRIPTION
**Pull request by jjasghar**
Started out with 3 Questions:
- The defaults are way too small or missing something, how do I change the default Vagrant machine?
- How do I add another driver other than Vagrant?
- When would I want to use .kitchen.local.yml or .kitchen.cloud.yml?

TODO
- [x] How do I update test-kitchen inside ChefDK?
- [x] Good to go :metal:

### CODE REVIEW

**Comment by mwrock** [comment]
:100: I think this could be merged as is and we iterate on it eternally.

**Comment by jjasghar** [comment]
I'd like that "update test-kitchen" question. I don't actually know, hence the TODO. :metal:

**Comment by mwrock** [comment]
oh I mentioned it here: https://discourse.chef.io/t/updating-to-test-kitchen-1-6-0-in-a-chefdk-0-11-2-or-lesser/7899. You could do some copy pasta here.

**Comment by jjasghar** [comment]
Awesome! I'll update it ASAP.

**Comment by jjasghar** [comment]
Shall we merge? Also @robbkidd i believe you have the rights to update the kichen.ci site?

**Comment by robbkidd** [comment]
👍

**Comment by robbkidd** [comment]
:shipit:

**Pull request merged**
